gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
  showCommandLog: false

keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<esc>'
  files:
    up: 'k'
    down: 'j'
    toggleStaged: 'space'
    commitChanges: 'cc'
  branches:
    checkoutBranch: 'enter'
    deleteBranch: 'd'
    up: 'k'
    down: 'j'
  commits:
    up: 'k'
    down: 'j'
  stash:
    up: 'k'
    down: 'j'
  global:
    prevTab: 'h'
    nextTab: 'l'
    gotoTop: 'gg'
    gotoBottom: 'G'
